// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aslgmyrizicjcdxvuysd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbGdteXJpemljamNkeHZ1eXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MjA4NDksImV4cCI6MjA1MTk5Njg0OX0.O3M_vbSCf7zaWO1CZG91voWm2177FMqT-cmJYvCeefY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);